# Generated by Django 5.1.3 on 2024-12-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_stock_quantity_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидается'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='pending', max_length=10),
        ),
    ]
