# Generated by Django 5.1.3 on 2024-12-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_stock_quantity_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='musicstore/media/products/', verbose_name='Изображение товара'),
        ),
    ]
